travis:
  secure:
    BINSTAR_TOKEN: ISkMddzAbn8OUEVPLjY+iLVXEBP/Q8s2y9mpJwcIXRWJkmuCBdwWUQQ6+YGZEL+H9DTL8XCUadCcLCquQq9HX6Ikbnl8ABdgRfka9MXa9kc18qBhPGNUJYguGuMZBCb54stPwyvM2nR+lEv0LJwFaJX5iBWTn4xx4pIvmZ8gSer1kyrnSnd0Vpyjdl3qSzrG+VFlb+pPw1eTpIhWMSzXLUDWv1Yte0fIWRDSgAYZZV3ewdzhzhLMYb89JQeL5ZLULgscEKtSnMQrwiUasSTkCwqmBcdtT8ZttBETGC2guU36voaPDQbGnnjtJ1olV9iesApyGoVtG/pj90sPioKAxWCO49GRx8x624WlF1mU4TOPpYXCHZ6F1+lqwTPAufkk1wkXBfXgWqP6BpHxo09EdnOUWQaVWxnQX8uJZ/RNJiqyBGYkmWjG7zObUMqtegdYyojdwZkHBsNCNYsZHl+/7iPHecYmuNKo6DzhgYvvtkC6sXCFz1jwtlGPNA6fFb5fJl10ywJCWJfpgeLKESSnv8XsZMgvQxJNCEfCPxymGyhQf44pZMRlymYcfbMltgxw2PaZhuOEg0CF0xrTzyjmv6hDkegcMmcZfZAR7+tpZFlrXSWzMVXEqyDkBncsW1ufnm+lRbrl8n32NUSRGjrRuZDid+SVOlhqwPAbp+Xo14c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
